Repository angular-hispano/angular-hispano, pull requests merged in 2019-06, with the labels that each got.

#47 style: configurar formato - stylelint, clang-format. ajustes de VSCode
  .clang-format
  .gitignore
  .stylelintrc
  .vscode/README.md
  .vscode/extensions.json
  .vscode/settings.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  projects/web/src/app/app.component.spec.ts
  projects/web/src/app/app.component.ts
  projects/web/src/app/app.module.ts
  projects/web/src/app/code-of-conduct/code-of-conduct.component.scss
  projects/web/src/app/code-of-conduct/code-of-conduct.component.spec.ts
  projects/web/src/app/code-of-conduct/code-of-conduct.component.ts
  projects/web/src/app/conferences/conferences.component.spec.ts
  projects/web/src/app/conferences/conferences.component.ts
  projects/web/src/app/footer/footer.component.scss
  projects/web/src/app/footer/footer.component.spec.ts
  projects/web/src/app/footer/footer.component.ts
  projects/web/src/app/landing/landing.component.scss
  projects/web/src/app/landing/landing.component.spec.ts
  projects/web/src/app/landing/landing.component.ts
  projects/web/src/app/nav.service.spec.ts
  projects/web/src/app/nav.service.ts
  projects/web/src/app/nav/nav.component.scss
  projects/web/src/app/nav/nav.component.spec.ts
  projects/web/src/app/nav/nav.component.ts
  projects/web/src/app/page-not-found/page-not-found.component.spec.ts
  projects/web/src/app/page-not-found/page-not-found.component.ts
  projects/web/src/app/sponsors/sponsors.component.scss
  projects/web/src/app/sponsors/sponsors.component.ts
  projects/web/src/app/top-nav/top-nav.component.scss
  projects/web/src/app/top-nav/top-nav.component.spec.ts
  projects/web/src/app/top-nav/top-nav.component.ts
  projects/web/src/environments/environment.ts
  projects/web/src/main.ts
  projects/web/src/polyfills.ts
  projects/web/src/styles.scss
  projects/web/src/test.ts
  tools/stylelint/no-ampersand-beyond-selector-start/index.js
  tools/stylelint/no-concrete-rules/index.js
  tools/stylelint/no-nested-mixin/index.js
  tools/stylelint/no-prefixes/needs-prefix.js
  tools/stylelint/no-prefixes/no-prefixes.js
  tools/stylelint/no-top-level-ampersand-in-mixin/index.js
  tools/stylelint/selector-no-deep/index.js
Labels: mejora

#59 chore: quitar ESLint extension para VSCode
  .vscode/extensions.json
Labels: defecto

#60 build: update browserslist
  projects/web/browserslist
Labels: mejora

#65 docs(contributing): cambio de palabras
  CONTRIBUTING.md
Labels: defecto

#62 feat(conferences): añadir ciudad y país a los tarjetas
  projects/web/src/app/conferences/conferences.component.html
  projects/web/src/app/conferences/conferences.component.scss
  projects/web/src/app/conferences/conferences.component.ts
Labels: pr: en progreso

#67 feat(meetups): organizar meetups
  projects/web/src/app/app.module.ts
  projects/web/src/app/nav/nav.component.html
  projects/web/src/app/organize-meetup/organize-meetup.component.html
  projects/web/src/app/organize-meetup/organize-meetup.component.scss
  projects/web/src/app/organize-meetup/organize-meetup.component.spec.ts
  projects/web/src/app/organize-meetup/organize-meetup.component.ts
Labels: mejora
