Repository angular-hispano/angular-hispano, pull requests merged in 2019-11, with the labels that each got.

#86 feat(pwa): implementa service worker y manifiest para activar pwa
  angular.json
  package-lock.json
  package.json
  projects/web/ngsw-config.json
  projects/web/src/app/app.module.ts
  projects/web/src/assets/icons/icon-128x128.png
  projects/web/src/assets/icons/icon-144x144.png
  projects/web/src/assets/icons/icon-152x152.png
  projects/web/src/assets/icons/icon-192x192.png
  projects/web/src/assets/icons/icon-384x384.png
  projects/web/src/assets/icons/icon-512x512.png
  projects/web/src/assets/icons/icon-72x72.png
  projects/web/src/assets/icons/icon-96x96.png
  projects/web/src/index.html
  projects/web/src/manifest.webmanifest
Labels: mejora

#90 Implementación de Husky para correr scripts previo a commits or push
  package-lock.json
  package.json
Labels: mejora

#93 fix(pwa): correcciones de pruebas en producción
  angular.json
  firebase.json
  projects/web/ngsw-config.json
  projects/web/src/app/conferences/conferences.component.ts
  projects/web/src/apple-touch-icon.png
  projects/web/src/assets/icons/android-chrome-192x192.png
  projects/web/src/assets/icons/android-chrome-512x512.png
  projects/web/src/assets/icons/browserconfig.xml
  projects/web/src/assets/icons/favicon-16x16.png
  projects/web/src/assets/icons/favicon-32x32.png
  projects/web/src/assets/icons/icon-128x128.png
  projects/web/src/assets/icons/icon-144x144.png
  projects/web/src/assets/icons/icon-152x152.png
  projects/web/src/assets/icons/icon-192x192.png
  projects/web/src/assets/icons/icon-384x384.png
  projects/web/src/assets/icons/icon-512x512.png
  projects/web/src/assets/icons/icon-72x72.png
  projects/web/src/assets/icons/icon-96x96.png
  projects/web/src/assets/icons/mstile-144x144.png
  projects/web/src/assets/icons/mstile-150x150.png
  projects/web/src/assets/icons/mstile-310x150.png
  projects/web/src/assets/icons/mstile-310x310.png
  projects/web/src/assets/icons/mstile-70x70.png
  projects/web/src/assets/icons/safari-pinned-tab.svg
  projects/web/src/assets/ng-honduras-logo.svg
  projects/web/src/favicon.ico
  projects/web/src/index.html
  projects/web/src/manifest.webmanifest
Labels: defecto

#96 build: activar strict TypeScript y Angular compiler options
  tsconfig.json
Labels: propuesta

#95 chore: nuevos extensiones recomendados
  .vscode/extensions.json
Labels: mejora
